CREATE TABLE IF NOT EXISTS watchlist (
  symbol TEXT PRIMARY KEY NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS daily_runs (
  run_date TEXT PRIMARY KEY NOT NULL,
  status TEXT NOT NULL,
  completed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);
